#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

#define DRIVER_EXPECTED_SYSCLK_HZ       64000000u
#define DRIVER_PWM_CARRIER_HZ           14000u
#define DRIVER_PWM_DYNAMIC_6STEP_ENABLE 1u
#define DRIVER_PWM_6STEP_TARGET_PULSES_PER_SECTOR 12u
#define DRIVER_PWM_6STEP_MIN_CARRIER_HZ DRIVER_PWM_CARRIER_HZ
#define DRIVER_PWM_6STEP_MAX_CARRIER_HZ 128000u
#define DRIVER_CONTROL_LOOP_HZ          10000u
#define DRIVER_SIN_TABLE_STEPS          256u
#define DRIVER_SIN_TABLE_MAX_VALUE      1049u
#define DRIVER_BEMF_LED_DIAGNOSTIC_ONLY 0u
#define DRIVER_TEST_BLIND_6STEP_ONLY   1u
#define DRIVER_SIXSTEP_BEMF_MONITOR_ONLY 0u
#define DRIVER_BLIND_6STEP_RPM         1200
#define DRIVER_BLIND_6STEP_DUTY_PERMILLE 150u
#define DRIVER_BLIND_6STEP_CLOSED_LOOP_DUTY_PERMILLE 295u
#define DRIVER_BLIND_6STEP_BEMF_ADVANCE_DEG_X10 300u
#define DRIVER_BLIND_6STEP_CLOSED_LOOP_HANDOFF_STEPS 6u
#define DRIVER_BLIND_6STEP_START_STEP  1u
#define DRIVER_SIXSTEP_SPEED_CONTROL_DIVIDER_TICKS 10u
#define DRIVER_SIXSTEP_SPEED_KP_ERPM_PER_PWM_TICK 96u
#define DRIVER_SIXSTEP_SPEED_MAX_STEP_TICKS 8u
#define DRIVER_SIXSTEP_CLOSED_LOOP_MIN_DUTY_PERMILLE 0u
#define DRIVER_OPEN_LOOP_SINUS_RPM      300
#define DRIVER_OPEN_LOOP_START_RPM      100
#define DRIVER_OPEN_LOOP_ALIGN_MS       800u
#define DRIVER_OPEN_LOOP_RAMP_RPM_PER_SEC 200u
#define DRIVER_OPEN_LOOP_MAX_DUTY_PERMILLE 70u
#define DRIVER_OPEN_LOOP_6STEP_MAX_DUTY_PERMILLE 70u
#define DRIVER_SIN_TO_6STEP_SETTLE_MECH_REV 1u
#define DRIVER_SIXSTEP_BEMF_ARM_DELAY_MS 1200u
#define DRIVER_SIXSTEP_BEMF_ARM_AFTER_MECH_REV 2u
#define DRIVER_SIXSTEP_BEMF_ARM_AFTER_STEPS 12u
#define DRIVER_SIXSTEP_BEMF_BLANK_TICKS 2u
#define DRIVER_SIXSTEP_BEMF_POLLING_CHANGEOVER_TICKS 2000u
#define DRIVER_SIXSTEP_BEMF_POLL_COUNT  2u
#define DRIVER_SIXSTEP_BEMF_OK_COUNT    6u
#define DRIVER_SIXSTEP_BEMF_LOCK_EXTRA_COUNT 0u
#define DRIVER_BEMF_PHASE_MAP_SHIFT     0u
#define DRIVER_NVM_FLASH_MARKER         0x424C4443u
#define DRIVER_NVM_STRUCT_VERSION       4u

typedef enum
{
    MOTOR_DIRECTION_CW = 0,
    MOTOR_DIRECTION_CCW = 1
} motor_direction_t;

#define DRIVER_OPEN_LOOP_DIRECTION      MOTOR_DIRECTION_CW

typedef enum
{
    MOTOR_MODE_STOP = 0,
    MOTOR_MODE_SINUS = 1,
    MOTOR_MODE_SIXSTEP = 2
} motor_mode_t;

#endif
